### ISSUE TITLE
Release plan after v1.4.8

### ISSUE THREAD

**Issue by takatea** [omrikiei/ktunnel#93]
Hi, @omrikiei !

Could you tell me a next release plan if its plan had been decided?

Because I feel Ktunnel is the awesome cli tool that it establishes a reverse tunnel very easy, I would like to recommend Ktunnel to my co-workers.
Therefore, I would like to install the binary of the latest master version more easily without building on any local machine.

Thank you in advance.

**Comment by omrikiei** [comment]
Hi @takatea,
Firstly, thank you for the kind words! knowing that ktunnel has improved other people's experience with k8s is one of the greatest feelings to have experienced.

As for the next release plan, there isn't one.. I don't know.. 
As can be seen, it's been a while since I've pushed code into ktunnel, most of the recent commits were bug fixes and minor proposals from users. I don't have any plans for improving it as I'm no longer personally using it (my focus has shifted towards other things). Nevertheless if there are specific requests for features that you think can improve and benefit all users of ktunnel I may implement those, and off course I would love to have additional people contribute code.

Thank you again!

**Comment by takatea** [comment]
@omrikiei, thank you for the reply!
I meant that I would like to the current master branch just with merged #92 to be released as v1.4.9.
Can I help you if you have any blockers to release the current master branch?

Thank you in advance!
